name: Spring Boot CI + Deploy

on:
  push:
    branches:
      - main
      - dev
      - feature/**
  pull_request:
    branches:
      - main
      - dev
      - feature/**

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build JAR (skip tests)
        run: mvn clean package -DskipTests

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy JAR to Server
        run: |
          JAR_FILE=$(ls target/*.jar | head -n 1)
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
            scp -o StrictHostKeyChecking=no \
            "$JAR_FILE" \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/root/app.jar

      - name: Reload app with PM2
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
              echo 'Reloading Spring Boot App using PM2...'
              pm2 reload spring-app || pm2 start 'java -jar /root/app.jar --server.port=3030' --name spring-app
              pm2 save
              pm2 status
            "
